### ISSUE TITLE
Update docker-compose.yml

### ISSUE THREAD

**Issue by Xanagandr** [Kong/docker-kong#112]
The current 'docker-compose.yml' file is for docker-compose version 2, yet docker-compose is currently running on version 3.3, and there are a lot of deprecated commands and syntax changes that need to take place for this docker-compose file to run on current versions.

**Comment by cosmopetrich** [comment]
I don't believe that version 2 is deprecated. It's still being updated. The most recent version of docker-compose added version 2.3.

3.x is only intended for use with Docker Swarm. 2.x still appears to be preferred for usage outside swarm. Is it actually worth updating this compose file to handle Swarm given that it would take some non-trivial modifications to work around [the inability to use health checks to control ordering](https://docs.docker.com/compose/startup-order/) in 3.x?

**Comment by amifeanyi** [comment]
I think the docker-compose version needs to be updated am running on docker-compose version 1.8.0 and it throws this error:

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

And when u specify version 2 more errors

**Comment by amifeanyi** [comment]
When you specify version 2:

ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.consul: 'healthcheck'
Unsupported config option for services.kong: 'healthcheck'
Unsupported config option for services.kong-database: 'healthcheck'
services.nginx-lb.depends_on contains an invalid type, it should be an array
services.kong-migration.depends_on contains an invalid type, it should be an array
services.kong.depends_on contains an invalid type, it should be an array

**Comment by antwan2093** [comment]
Did you ever resolve this issue? Getting stuck here too...

**Comment by prolic** [comment]
you have to remove the health_check stuff, this is no longer supported with newer docker versions

**Comment by prolic** [comment]
I hope to be able to submit a PR soon for this

**Comment by hutchic** [comment]
I'm going to close this issue as I don't think it's something we (Kong) are going to resolve. At this time Docker Swarm is kind of abandoned / loosing traction and our v2 docker-compose file works for all use cases excluding docker swarm.

If someone wants to submit a PR that up's our docker-compose to v3 without breaking current functionality would absolutely consider it 👍

**Comment by hutchic** [comment]
A PR exists for this now https://github.com/Kong/docker-kong/pull/250
