### ISSUE TITLE
compose_kong_1 exited with code 1

### ISSUE THREAD

**Issue by wownepiece** [Kong/docker-kong#127]
##_docker-compose up_
then
```
....
kong_1            | 2017/12/05 02:54:43 [warn] postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
kong_1            | Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!
kong_1            |
kong_1            |   Run with --v (verbose) or --vv (debug) for more details
compose_kong_1 exited with code 1
...
```
## _docker logs compose_kong_1_
```
2017/12/05 02:54:43 [warn] postgres database 'kong' is missing migration: (response-transformer) 2016-05-04-160000_resp_trans_schema_changes
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:28: [postgres error] the current database schema does not match this version of Kong. Please run `kong migrations up` to update/initialize the database schema. Be aware that Kong migrations should only run from a single node, and that nodes running migrations concurrently will conflict with each other and might corrupt your database schema!

  Run with --v (verbose) or --vv (debug) for more details
prefix directory /usr/local/kong not found, trying to create it
```
## docker -v
`Docker version 1.12.6, build 78d1802`

it works well on my laptop with docker version 1.17,   is that the problem?

**Comment by wownepiece** [comment]
[installation guid with docker run commands](https://getkong.org/install/docker/) works
:(

**Comment by rmetcalf9** [comment]
I get this error. I think it is because the kong service starts when the kong-migration condition is service-started.
I checked through my compose log and I can see that the kong-migration is still ongoing when kong is starting up. What we need is a way to make the kong service depend_on condition to be service completed rather than service_started.
I don't think the service_completed tag actually exists though, but I am still researching.

**Comment by LogansUA** [comment]
Have the same issue. Somebody found the solution?

**Comment by rmetcalf9** [comment]
I simply have restart on failure set so that when the docker stack is comming to life it will try starting Kong a number of times until it finally succeeds.
See an example of a compose file I am using in my current project:
https://github.com/rmetcalf9/dockJob/blob/master/composeExamples/docker-compose-https-basic-auth.yml
It's not an elegant solution. I have cinsidered preforming a Kong migration on the postgress database and storing that database image. That approach has other issues though.

**Comment by liyuntao** [comment]
you should add `command: 'kong start --run-migrations'`  under service kong in docker-compose.yml

**Comment by rmetcalf9** [comment]
Hi,
You can see from my docker compose file (linked) that I use the command:
```
kong migrations up
```
This executes kong and then terminates when it is complete. I have another container that runs and executes kong.

What is the behavour/difference with the option
```
kong start --run-migrations
```
Will it terminate when the migrations are complete?
What happens if it runs and the migrations have already been done? 

I am trying to work out if this command will meet my requirments
Robert

**Comment by hutchic** [comment]
The kong migration commands are documented here [kong-migrations](https://docs.konghq.com/1.0.x/cli/#kong-migrations).

We now have tests that validate `docker-compose` so if this was broken it's not at this time so I'm going to close this issue
