### ISSUE TITLE
Kong Docker image is hanging at startup (on Kubernetes only)

### ISSUE THREAD

**Issue by pamiel** [Kong/docker-kong#258]
This issue is declared here to help people facing the same problem and searching it into this specific `docker-kong` repo, as the problem is specific to the deployment of Kong _as a Docker image_ (and more specifically in a Kubernetes environment).
However, the overall description is provided here https://github.com/Kong/kong/issues/4559.

A possible workaround (waiting for a more resilient implementation of the DNS query for Cassandra in Kong) is to insert a `sleep 5` or a fake DNS lookup (e.g. `nslookup fake`) in the `docker-entrypoint.sh` script before running the `nginx` command (e.g. at the very beginning of the script).

**Comment by hutchic** [comment]
thanks for the cross-link. I'm going to close this issue and continue debugging / investigating on the linked issue.

One point of clarity this is *ONLY* with Cassandra. We have functional tests that exercise Kong with postgres (the cassandra ones are a work in progress) so can say with certainty that this issue is isolated to Cassandra
