### ISSUE TITLE
Tags on Redhat container catalog appear incorrect

### ISSUE THREAD

**Issue by sfhardman** [Kong/docker-kong#339]
It looks like tagging on the Redhat container catalog is not working right.  I've pulled the image tagged '1.5.0' expecting to get Kong 1.5.0 but the image contains Kong 2.0.0.  Tag '1.4.2' has the expected Kong version, but the later ones [here](https://access.redhat.com/containers/?tab=tags#/registry.connect.redhat.com/kong/kong) all appear to be Kong 2.0.0 based on what shows in the 'package list' in the Redhat catalog website.

**Comment by hutchic** [comment]
looks like redhat muddled our version control sometime around 2.0.0.

We've since moved away from using their automated build service and instead build / push from our own infrastructure which includes tests to catch this and explains why all the tags after 2.0.0 are fine.

I've deleted the offending tags, build and pushed fixed tags with `-0` since it seems redhat repository won't let me overwrite existing tags
